# ╔══════════════════════════════════════════════════════════════╗
# ║          ✦ Lumière OS — pacman.conf                          ║
# ╚══════════════════════════════════════════════════════════════╝

[options]
HoldPkg     = pacman glibc
Architecture = x86_64
Color
CheckSpace
VerbosePkgLists
ParallelDownloads = 5
SigLevel    = Required DatabaseOptional
LocalFileSigLevel = Optional

# ─── Repolar ────────────────────────────────────────────────────
[core]
Include = /etc/pacman.d/mirrorlist

[extra]
Include = /etc/pacman.d/mirrorlist

[multilib]
Include = /etc/pacman.d/mirrorlist
